import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link';

import Sidebar from "./components/Sidebar";
import BottomBar from "./components/BottomBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} custom-div`}>
        <div className="min-h-screen w-screen flex flex-col md:flex-row">
          <Sidebar />

          <main className="h-full w-full md:max-h-screen md:w-full">
            {children}
          </main>
          <div className="md:hidden">
            <BottomBar />
          </div>
        </div>
      </body>
    </html>
  );
}
